### ISSUE TITLE
configparser needs to be declared a dependence

### ISSUE THREAD

**Issue by alurban** [gwdetchar/gwdetchar#100]
At the very least, `gwdetchar-omega` will fail without `configparser`, so it needs to be declared an explicit code dependence.

**Comment by duncanmmacleod** [comment]
@aurban, `configparser` is part of the standard library, so should always be present. Do you have an example of this being not the case?

**Comment by alurban** [comment]
@duncanmmacleod, yesterday I tried building a fresh virtual environment on `ldas-pcdev1.ligo-la.caltech.edu` that somehow didn't inherit `configparser`:
```
[]$ virtualenv --system-site-packages ~/opt/hveto-dev
[]$ . ~/opt/hveto-dev/bin/activate
[]$ pip show configparser
[]$ 
```

**Comment by duncanmmacleod** [comment]
`configparser` is the python3 name for what in python2 is called `ConfigParser`. It's also not a package, so you can't `pip show` it (AFAIK), the test should be

```
python2.7 -c "import ConfigParser"
```

**Comment by alurban** [comment]
I'm confused by your last sentence, because I did exactly those things yesterday, in fact if I check it now I see this:
```
(hveto-dev) []$ pip install configparser
Requirement already satisfied: configparser in ./opt/hveto-dev/lib/python2.7/site-packages (3.5.0)
(hveto-dev) []$ pip show configparser
Name: configparser
Version: 3.5.0
Summary: This library brings the updated configparser from Python 3.5 to Python 2.6-3.5.
Home-page: http://docs.python.org/3/library/configparser.html
Author: Lukasz Langa
Author-email: lukasz@langa.pl
License: MIT
Location: /home/aurban/opt/hveto-dev/lib/python2.7/site-packages
Requires: 
Required-by: 
```

**Comment by alurban** [comment]
Ah, it looks like I've inadvertently installed a backport: https://pypi.org/project/configparser/. So it looks like the real issue is that my code doesn't work with the 2.7 version of `ConfigParser`, do you have strong objections to adding `configparser` as a dependence for now until we are properly 3.6+ ready? It's funky that it has the same name as a native module.

**Comment by duncanmmacleod** [comment]
I feel strongly that the code should work with the standard library packages. What doesn't work with `ConfigParser`?

**Comment by alurban** [comment]
It comes at the step of trying to build an `OmegaChannelList`:
```
----------------------------------------------
Creating L1 omega scan at GPS second 1172489783.070...
Output directory created as /home/aurban/public_html/wdq/L1_1172489783.07
Traceback (most recent call last):
  File "/home/aurban/opt/hveto-dev/bin/gwdetchar-omega", line 297, in <module>
    blocks = [OmegaChannelList(**cp[s]) for s in cp.sections()]
AttributeError: OmegaConfigParser instance has no attribute '__getitem__'
```

**Comment by alurban** [comment]
@duncanmmacleod, turns out this wasn't so difficult, the issue was that in python2 the config parser can't be indexed by section name (I resolved it in #103 by passing `dict(cp.items(section))`).
